version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'doctor'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      - '3306'
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
  web:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "80:80"
    links:
      - app
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
  app:
    build: .
    links:
      - db
    ports:
      - "8080:8080"
volumes:
  dbdata:
