export const DataGridColumnDefinition = [
  { field: 'col1', headerName: 'Change Type', width: 150 },
  { field: 'col2', headerName: 'Covered Recipient Type', width: 150 },
  { field: 'col3', headerName: 'Teaching Hospital CCN', width: 150 },
  { field: 'col4', headerName: 'Teaching Hospital ID', width: 150 },
  { field: 'col5', headerName: 'Teaching Hospital Name', width: 150 },
  { field: 'col6', headerName: 'Physician Profile ID', width: 150 },
  { field: 'col7', headerName: 'Physician First Name', width: 150 },
  { field: 'col8', headerName: 'Physician Middle Name', width: 150 },
  { field: 'col9', headerName: 'Physician Last Name', width: 150 },
  { field: 'col10', headerName: 'Physician Name Suffix', width: 150 },
  { field: 'col11', headerName: 'Recipient Primary Business Street 1', width: 150 },
  { field: 'col12', headerName: 'Recipient Primary Business Street 2', width: 150 },
  { field: 'col13', headerName: 'Recipient City', width: 150 },
  { field: 'col14', headerName: 'Recipient State', width: 150 },
  { field: 'col15', headerName: 'Recipient Zip Code', width: 150 },
  { field: 'col16', headerName: 'Recipient Country', width: 150 },
  { field: 'col17', headerName: 'Recipient Province', width: 150 },
  { field: 'col18', headerName: 'Recipient Postal Code', width: 150 },
  { field: 'col19', headerName: 'Physician Primary Type', width: 150 },
  { field: 'col20', headerName: 'Physician Specialty', width: 150 },
  { field: 'col21', headerName: 'Physician License State Code 1', width: 150 },
  { field: 'col22', headerName: 'Physician License State Code 2', width: 150 },
  { field: 'col23', headerName: 'Physician License State Code 3', width: 150 },
  { field: 'col24', headerName: 'Physician License State Code 4', width: 150 },
  { field: 'col25', headerName: 'Physician License State Code 5', width: 150 },
  { field: 'col26', headerName: 'Manufacturer or GPO Name', width: 150 },
  { field: 'col27', headerName: 'Manufacturer or GPI Payment ID', width: 150 },
  { field: 'col28', headerName: 'Manufacturer or GPO Payment Name', width: 150 },
  { field: 'col29', headerName: 'Manufacturer or GPO Payment State', width: 150 },
  { field: 'col30', headerName: 'Manufacturer or GPO Payment Country', width: 150 },
  { field: 'col31', headerName: 'Total Dollar Amount', width: 150 },
  { field: 'col32', headerName: 'Date of Payment', width: 150 },
  { field: 'col33', headerName: 'Number of Payments for Total', width: 150 },
  { field: 'col34', headerName: 'Form of Payment', width: 150 },
  { field: 'col35', headerName: 'Nature of Payment', width: 150 },
  { field: 'col36', headerName: 'City of Travel', width: 150 },
  { field: 'col37', headerName: 'State of Travel', width: 150 },
  { field: 'col38', headerName: 'Country of Travel', width: 150 },
  { field: 'col39', headerName: 'Physician Owner Indicator', width: 150 },
  { field: 'col40', headerName: 'Third Party Payment', width: 150 },
  { field: 'col41', headerName: 'Entity Receiving', width: 150 },
  { field: 'col42', headerName: 'Charity Indicator', width: 150 },
  { field: 'col43', headerName: 'Third party Payment Recipient', width: 150 },
  { field: 'col44', headerName: 'Contextual Information', width: 150 },
  { field: 'col45', headerName: 'Delay in Publication', width: 150 },
  { field: 'col46', headerName: 'Record ID', width: 150 },
  { field: 'col47', headerName: 'Dispute Status for Publication', width: 150 },
  { field: 'col48', headerName: 'Product', width: 150 },
  { field: 'col49', headerName: 'Associated Covered Drug or Bio 1', width: 150 },
  { field: 'col50', headerName: 'Associated Covered Drug or Bio 2', width: 150 },
  { field: 'col51', headerName: 'Associated Covered Drug or Bio 3', width: 150 },
  { field: 'col52', headerName: 'Associated Covered Drug or Bio 4', width: 150 },
  { field: 'col53', headerName: 'Associated Covered Drug or Bio 5', width: 150 },
  { field: 'col54', headerName: 'NDC of Drug or Bio 1', width: 150 },
  { field: 'col55', headerName: 'NDC of Drug or Bio 2', width: 150 },
  { field: 'col56', headerName: 'NDC of Drug or Bio 3', width: 150 },
  { field: 'col57', headerName: 'NDC of Drug or Bio 4', width: 150 },
  { field: 'col58', headerName: 'NDC of Drug or Bio 5', width: 150 },
  { field: 'col59', headerName: 'Name of Device or Medial Supply 1', width: 150 },
  { field: 'col60', headerName: 'Name of Device or Medial Supply 2', width: 150 },
  { field: 'col61', headerName: 'Name of Device or Medial Supply 3', width: 150 },
  { field: 'col62', headerName: 'Name of Device or Medial Supply 4', width: 150 },
  { field: 'col63', headerName: 'Name of Device or Medial Supply 5', width: 150 },
  { field: 'col64', headerName: 'Program year', width: 150 },
  { field: 'col65', headerName: 'Payment Publication Date', width: 150 },
];
