import {COLUMNS} from '../../forms/model/SearchModels';

export const DataGridColumnDefinition = [
  { field: COLUMNS.changeType, headerName: 'Change Type', width: 150 },
  { field: COLUMNS.coveredRecipientType, headerName: 'Covered Recipient Type', width: 150 },
  { field: COLUMNS.teachingHospitalCCN, headerName: 'Teaching Hospital CCN', width: 150 },
  { field: COLUMNS.teachingHospitalId, headerName: 'Teaching Hospital ID', width: 150 },
  { field: COLUMNS.teachingHospitalName, headerName: 'Teaching Hospital Name', width: 150 },
  { field: COLUMNS.physicianProfileId, headerName: 'Physician Profile ID', width: 150 },
  { field: COLUMNS.physicianFirstName, headerName: 'Physician First Name', width: 150 },
  { field: COLUMNS.physicianMiddleName, headerName: 'Physician Middle Name', width: 150 },
  { field: COLUMNS.physicianLastName, headerName: 'Physician Last Name', width: 150 },
  { field: COLUMNS.physicianNameSuffix, headerName: 'Physician Name Suffix', width: 150 },
  { field: COLUMNS.recipientPrimaryBusinessStreet1, headerName: 'Recipient Primary Business Street 1', width: 150 },
  { field: COLUMNS.recipientPrimaryBusinessStreet2, headerName: 'Recipient Primary Business Street 2', width: 150 },
  { field: COLUMNS.recipientCity, headerName: 'Recipient City', width: 150 },
  { field: COLUMNS.recipientState, headerName: 'Recipient State', width: 150 },
  { field: COLUMNS.recipientZipCode, headerName: 'Recipient Zip Code', width: 150 },
  { field: COLUMNS.recipientCountry, headerName: 'Recipient Country', width: 150 },
  { field: COLUMNS.recipientProvince, headerName: 'Recipient Province', width: 150 },
  { field: COLUMNS.recipientPostalCode, headerName: 'Recipient Postal Code', width: 150 },
  { field: COLUMNS.physicianPrimaryType, headerName: 'Physician Primary Type', width: 150 },
  { field: COLUMNS.physicianSpecialty, headerName: 'Physician Specialty', width: 150 },
  { field: COLUMNS.physicianLicenseStateCode1, headerName: 'Physician License State Code 1', width: 150 },
  { field: COLUMNS.physicianLicenseStateCode2, headerName: 'Physician License State Code 2', width: 150 },
  { field: COLUMNS.physicianLicenseStateCode3, headerName: 'Physician License State Code 3', width: 150 },
  { field: COLUMNS.physicianLicenseStateCode4, headerName: 'Physician License State Code 4', width: 150 },
  { field: COLUMNS.physicianLicenseStateCode5, headerName: 'Physician License State Code 5', width: 150 },
  { field: COLUMNS.submittingApplicableManufacturerOrGpoName, headerName: 'Manufacturer or GPO Name', width: 150 },
  { field: COLUMNS.applicableManufacturerOrGpoPaymentId, headerName: 'Manufacturer or GPI Payment ID', width: 150 },
  { field: COLUMNS.applicableManufacturerOrGpoPaymentName, headerName: 'Manufacturer or GPO Payment Name', width: 150 },
  { field: COLUMNS.applicableManufacturerOrGpoPaymentState, headerName: 'Manufacturer or GPO Payment State', width: 150 },
  { field: COLUMNS.applicableManufacturerOrGpoPaymentCountry, headerName: 'Manufacturer or GPO Payment Country', width: 150 },
  { field: COLUMNS.totalAmountOfPaymentUsDollars, headerName: 'Total Dollar Amount', width: 150 },
  { field: COLUMNS.dateOfPayment, headerName: 'Date of Payment', width: 150 },
  { field: COLUMNS.numberOfPaymentsInTotalAmount, headerName: 'Number of Payments for Total', width: 150 },
  { field: COLUMNS.formOfPaymentOrTransferOfValue, headerName: 'Form of Payment', width: 150 },
  { field: COLUMNS.natureOfPaymentOrTransferOfValue, headerName: 'Nature of Payment', width: 150 },
  { field: COLUMNS.cityOfTravel, headerName: 'City of Travel', width: 150 },
  { field: COLUMNS.stateOfTravel, headerName: 'State of Travel', width: 150 },
  { field: COLUMNS.countryOfTravel, headerName: 'Country of Travel', width: 150 },
  { field: COLUMNS.physicianOwnershipIndicator, headerName: 'Physician Owner Indicator', width: 150 },
  { field: COLUMNS.thirdPartyPaymentRecipientIndicator, headerName: 'Third Party Payment', width: 150 },
  { field: COLUMNS.nameOfEntityReceivingPaymentOrTransferOfValue, headerName: 'Entity Receiving', width: 150 },
  { field: COLUMNS.charityIndicator, headerName: 'Charity Indicator', width: 150 },
  { field: COLUMNS.thirdPartyEqualsCoveredRecipientIndicator, headerName: 'Third party Payment Recipient', width: 150 },
  { field: COLUMNS.contextualInformation, headerName: 'Contextual Information', width: 150 },
  { field: COLUMNS.delayInPublicationIndicator, headerName: 'Delay in Publication', width: 150 },
  { field: COLUMNS.recordId, headerName: 'Record ID', width: 150 },
  { field: COLUMNS.disputeStatusForPublication, headerName: 'Dispute Status for Publication', width: 150 },
  { field: COLUMNS.productIndicator, headerName: 'Product', width: 150 },
  { field: COLUMNS.nameOfAssociatedCoveredDrugOrBiological1, headerName: 'Associated Covered Drug or Bio 1', width: 150 },
  { field: COLUMNS.nameOfAssociatedCoveredDrugOrBiological2, headerName: 'Associated Covered Drug or Bio 2', width: 150 },
  { field: COLUMNS.nameOfAssociatedCoveredDrugOrBiological3, headerName: 'Associated Covered Drug or Bio 3', width: 150 },
  { field: COLUMNS.nameOfAssociatedCoveredDrugOrBiological4, headerName: 'Associated Covered Drug or Bio 4', width: 150 },
  { field: COLUMNS.nameOfAssociatedCoveredDrugOrBiological5, headerName: 'Associated Covered Drug or Bio 5', width: 150 },
  { field: COLUMNS.ndcOfAssociatedCoveredDrugOrBiological1, headerName: 'NDC of Drug or Bio 1', width: 150 },
  { field: COLUMNS.ndcOfAssociatedCoveredDrugOrBiological2, headerName: 'NDC of Drug or Bio 2', width: 150 },
  { field: COLUMNS.ndcOfAssociatedCoveredDrugOrBiological3, headerName: 'NDC of Drug or Bio 3', width: 150 },
  { field: COLUMNS.ndcOfAssociatedCoveredDrugOrBiological4, headerName: 'NDC of Drug or Bio 4', width: 150 },
  { field: COLUMNS.ndcOfAssociatedCoveredDrugOrBiological5, headerName: 'NDC of Drug or Bio 5', width: 150 },
  { field: COLUMNS.nameOfAssociatedCoveredDeviceOrMedicalSupply1, headerName: 'Name of Device or Medial Supply 1', width: 150 },
  { field: COLUMNS.nameOfAssociatedCoveredDeviceOrMedicalSupply2, headerName: 'Name of Device or Medial Supply 2', width: 150 },
  { field: COLUMNS.nameOfAssociatedCoveredDeviceOrMedicalSupply3, headerName: 'Name of Device or Medial Supply 3', width: 150 },
  { field: COLUMNS.nameOfAssociatedCoveredDeviceOrMedicalSupply4, headerName: 'Name of Device or Medial Supply 4', width: 150 },
  { field: COLUMNS.nameOfAssociatedCoveredDeviceOrMedicalSupply5, headerName: 'Name of Device or Medial Supply 5', width: 150 },
  { field: COLUMNS.programYear, headerName: 'Program year', width: 150 },
  { field: COLUMNS.paymentPublicationDate, headerName: 'Payment Publication Date', width: 150 },
];
